seeds:
  graph: 80
  passengers: 67
  algorithm: 82

experiments:
  - passenger_params:
      num_passengers: 200
      service_hours: 24
      alpha: 10
      beta: 10
      preference_distribution: "peak_hours"
      inter_cluster_travelling: True

    graph_params:
      dataset: "westminster_hackney_stops"
      centroid_codes: [490003384SA, 490009644E]
      num_locations: [60, 60]
      short_avg_vehicle_speed: 19.76
      long_avg_vehicle_speed: 48

    optimiser_params:
      algorithm: 'greedy insert ++'
      algorithm_params:
        final_voting_rule: "none"
        iterations: 100
        objective: "gini_index"

    experiment_params:
      runs: 100

  - passenger_params:
      num_passengers: 200
      service_hours: 24
      alpha: 10
      beta: 20
      preference_distribution: "peak_hours"
      inter_cluster_travelling: True

    graph_params:
      dataset: "westminster_hackney_stops"
      centroid_codes: [490003384SA, 490009644E]
      num_locations: [60, 60]
      short_avg_vehicle_speed: 19.76
      long_avg_vehicle_speed: 48

    optimiser_params:
      algorithm: 'greedy insert ++'
      algorithm_params:
        final_voting_rule: "none"
        iterations: 100
        objective: "gini_index"

    experiment_params:
      runs: 100

  - passenger_params:
      num_passengers: 200
      service_hours: 24
      alpha: 10
      beta: 30
      preference_distribution: "peak_hours"
      inter_cluster_travelling: True

    graph_params:
      dataset: "westminster_hackney_stops"
      centroid_codes: [490003384SA, 490009644E]
      num_locations: [60, 60]
      short_avg_vehicle_speed: 19.76
      long_avg_vehicle_speed: 48

    optimiser_params:
      algorithm: 'greedy insert ++'
      algorithm_params:
        final_voting_rule: "none"
        iterations: 100
        objective: "gini_index"

    experiment_params:
      runs: 100

  - passenger_params:
      num_passengers: 200
      service_hours: 24
      alpha: 20
      beta: 10
      preference_distribution: "peak_hours"
      inter_cluster_travelling: True

    graph_params:
      dataset: "westminster_hackney_stops"
      centroid_codes: [490003384SA, 490009644E]
      num_locations: [60, 60]
      short_avg_vehicle_speed: 19.76
      long_avg_vehicle_speed: 48

    optimiser_params:
      algorithm: 'greedy insert ++'
      algorithm_params:
        final_voting_rule: "none"
        iterations: 100
        objective: "gini_index"

    experiment_params:
      runs: 100

  - passenger_params:
      num_passengers: 200
      service_hours: 24
      alpha: 30
      beta: 10
      preference_distribution: "peak_hours"
      inter_cluster_travelling: True

    graph_params:
      dataset: "westminster_hackney_stops"
      centroid_codes: [490003384SA, 490009644E]
      num_locations: [60, 60]
      short_avg_vehicle_speed: 19.76
      long_avg_vehicle_speed: 48

    optimiser_params:
      algorithm: 'greedy insert ++'
      algorithm_params:
        final_voting_rule: "none"
        iterations: 100
        objective: "gini_index"

    experiment_params:
      runs: 100

