seeds:
  graph: 80
  passengers: 67
  algorithm: 82

optimiser_params:
  - algorithm: "RGA"
    algorithm_params: 
      objective: "gini_index"
      multiple_iterations: True
    
  - algorithm: "RGA ++"
    algorithm_params:
      objective: "gini_index"
      multiple_iterations: True
  
  - algorithm: "RGVA"
    algorithm_params:
      final_voting_rule: "borda_count"
  
  - algorithm: "RGVA"
    algorithm_params:
      final_voting_rule: "popularity"
  
  # - algorithm: "IV1"
  #   algorithm_params:
  #     iterative_voting_rule: "borda_count"
  #     final_voting_rule: "borda_count"

  - algorithm: "IV2"
    algorithm_params:
      iterative_voting_rule: "borda_count"
  
const_params:
  experiment_params:
    runs: 1
    name: "test"

  passenger_params:
    service_hours: 24
    num_passengers: 80
    inter_cluster_probability: 0
    alpha: 10
    beta: 10
    centroid_likelihood: 0
    peak_probability: 0.6
    time_step: 20
  
  graph_params:
    localities: ["Westminster", "Hackney"]
    num_locations: [66, 60]
    short_avg_vehicle_speed: 13
    long_avg_vehicle_speed: 48
  
var_params:
  passenger_params:
    num_passengers: [50, 80, 120]
    