seeds:
  graph: 80
  passengers: 67
  algorithm: 82

experiments:
  - passenger_params:
      num_passengers: 100
      service_hours: 24
      beta_distribution: "truncated_normal"
      preference_distribution: "uniform"
      inter_cluster_travelling: True

    graph_params:
      num_locations: 150
      clusters: 4
      min_location_distance: 400
      grid_size: 7000
      avg_vehicle_speed: 30

    optimiser_params:
      algorithm: 'greedy_insert'
      algorithm_params:
        iterations: 1
        final_voting_rule: "borda_count"

    experiment_params:
      runs: 10
      