seeds:
  graph: 80
  passengers: 67
  algorithm: 82

optimiser_params:
  - algorithm: "greedy insert"
    algorithm_params: 
      final_voting_rule: "none"
      iterations: 1
      objective: "gini_index"

  - algorithm: "greedy insert ++"
    algorithm_params:
      final_voting_rule: "none"
      iterations: 1
      objective: "gini_index"
  
  - algorithm: "iterative voting 2"
    algorithm_params:
      final_voting_rule: "none"
      iterative_voting_rule: "borda_count"
      iterations: 1
      objective: "gini_index"


const_params:
  experiment_params:
    runs: 1
    name: "num_passengers"

  passenger_params:
    service_hours: 24
    alpha: 10
    beta: 10
    inter_cluster_travelling: True
    peak_probability: 0.6
    time_step: 20
  
  graph_params:
    dataset: "westminster_hackney_stops"
    centroid_codes: [490003384SA, 490009644E]
    num_locations: [66, 60]
    short_avg_vehicle_speed: 13
    long_avg_vehicle_speed: 48
  
var_params:
  passenger_params:
    num_passengers: [50, 100, 150]