seeds:
  graph: 42
  passengers: 67
  algorithm: 82

experiments:
  # - passenger_params:
  #     num_passengers: 120
  #     service_hours: 16
  #     beta_distribution: "truncated_normal"
  #     preference_distribution: "peak_hours"
  #     inter_cluster_travelling: True

  #   graph_params:
  #     num_locations: 25
  #     clusters: 5
  #     grid_size: 1200
  #     avg_vehicle_speed: 14.96

  #   optimiser_params:
  #     algorithm: 'greedy_insert'
  #     algorithm_params:
  #       iterations: 5
  #       final_voting_rule: "borda_count"

  #   experiment_params:
  #     runs: 10
      
  - passenger_params:
      num_passengers: 25
      service_hours: 24
      beta_distribution: "truncated_normal"
      preference_distribution: "peak_hours"
      inter_cluster_travelling: True

    graph_params:
      num_locations: 25
      clusters: 5
      grid_size: 1200
      avg_vehicle_speed: 14.96

    optimiser_params:
      algorithm: 'iterative_voting_1'
      algorithm_params:
        iterative_voting_rule: 'borda_count'
        final_voting_rule: "borda_count"
        wait_time: 5

    experiment_params:
      runs: 5
