experiment_params:
    runs: 100
    name: "test_2"
    initial_passenger_seed: 67
    initial_algorithm_seed: 82

optimiser_params:
  - algorithm: "RGA"
    algorithm_params: {}

  - algorithm: "RGA ++"
    algorithm_params: {}

  - algorithm: "IV2"
    algorithm_params:
      iterative_voting_rule: "borda_count"

  - algorithm: "IV2"
    algorithm_params:
      iterative_voting_rule: "harmonic"

  - algorithm: "IV2"
    algorithm_params:
      iterative_voting_rule: "instant_runoff"

  - algorithm: "IV2"
    algorithm_params:
      iterative_voting_rule: "popularity"
  
const_params:
  passenger_params:
    alpha: 10
    beta: 10
    peak_probability: 0.8
    # num_hotspots: 10 
  
  graph_params:
    locality: Westminster
    num_locations: 60
    avg_vehicle_speed: 13
  
var_params:
  passenger_params:
    num_passengers: [50, 100, 150, 200]